# src/wscript
def options(opt):
    opt.load('compiler_cxx')
    
def configure(cfg):
    cfg.load('compiler_cxx')

def build(bld):
    deps = bld.env.SYSTEM_DEPS + [x.parent.name for x in bld.path.ant_glob('*/wscript')]
    type = bld.env.BUILD_TYPE
    bld(features = 'cxx cxxprogram', 
        source   = bld.path.ant_glob('*.cpp'), 
        target   = 'falltergeist', 
        use      = type + deps,
        linkflags = ['-Wl,-rpath,$ORIGIN/../lib', '-Wl,-z,origin']
    )
